baseURL = "http://lgaspar.pt"
languageCode = "pt-pt"
title = "Laurentino Gaspar"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"
publishDir = "docs"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "pt"

#Para por HTML puro no meio
#[markup.goldmark.renderer]
#unsafe= true

[params.info]
description = "Mediação de seguros"
title404 = "Por favor, volte atrás. Esta página não está disponível."

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Laurentino Gaspar- Mediador de Seguros, Lda."
startYear = "2021"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = true # boolean / array of sections
hideEntryMeta = false # boolean / array of sections
showReadingTime = true
showLastmod = false
taxonomyCloudShuffle = false
accentColor = "#006046"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "geral@lgaspar.pt"
facebook = "Laurentino-Gaspar-mediador-seguros-Lda-276742315789709"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
twitter = ""
telegram = "laurentinogasparseguros"
google_scholar = ""
youtube = ""

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "MunifTanjim"
repository = "minimo"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/MunifTanjim/minimo"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.pt]
lang = "pt"
languageName = "Portugues"
weight = 1
